### ISSUE TITLE
Modals do not open on iOS.

### ISSUE THREAD

**Issue by chloeeggleston** [AlexCaswell/RobluScouterWeb#1]
Browsers Tested: Safari, Chrome.

**Comment by AlexCaswell** [comment]
What server are you connecting to, and are you sure it contains an active event with checkouts?
Also, this project must be run on some sort of server as it uses php. If you are testing the app on a local server, you will need something to enable CORS requests like the chrome extension linked to in the readme.

If you do those things, you should be able to view and edit the checkouts in the same way as the android app. However, this project is still unfinished, and there is currently an issue with uploading back to the server.
